using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

public class Match
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)] // Specify that the 'id' is not generated by the database
    public int id { get; set; }
    public int team1_id { get; set; }
    public string team1_name { get; set; }
    public int team2_id { get; set; }
    public string team2_name { get; set; }
    public int? team1_score { get; set; }
    public int? team2_score { get; set; }
}